name: ${pluginName}
version: ${version}
main: net.refractored.simpleboosters.SimpleBoostersPlugin
authors:
  - refractored
api-version: 1.19

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false
